// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelBatch() {
  return window['go']['main']['App']['CancelBatch']();
}

export function CancelFile(arg1) {
  return window['go']['main']['App']['CancelFile'](arg1);
}

export function ClearFinishedTasks() {
  return window['go']['main']['App']['ClearFinishedTasks']();
}

export function ConvertText(arg1, arg2) {
  return window['go']['main']['App']['ConvertText'](arg1, arg2);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function PauseBatch() {
  return window['go']['main']['App']['PauseBatch']();
}

export function ResumeBatch() {
  return window['go']['main']['App']['ResumeBatch']();
}

export function RetryFailed() {
  return window['go']['main']['App']['RetryFailed']();
}

export function RetryFile(arg1) {
  return window['go']['main']['App']['RetryFile'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectInputDirectory() {
  return window['go']['main']['App']['SelectInputDirectory']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function SelectTextFiles() {
  return window['go']['main']['App']['SelectTextFiles']();
}

export function StartBatch(arg1) {
  return window['go']['main']['App']['StartBatch'](arg1);
}
