// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelBatch():Promise<void>;

export function CancelFile(arg1:number):Promise<void>;

export function ClearFinishedTasks():Promise<void>;

export function ConvertText(arg1:string,arg2:string):Promise<void>;

export function GetState():Promise<main.AppState>;

export function LoadConfig():Promise<main.ConfigPayload>;

export function PauseBatch():Promise<void>;

export function ResumeBatch():Promise<void>;

export function RetryFailed():Promise<void>;

export function RetryFile(arg1:number):Promise<void>;

export function SaveConfig(arg1:string):Promise<main.ConfigPayload>;

export function SelectInputDirectory():Promise<string>;

export function SelectOutputDir():Promise<string>;

export function SelectTextFiles():Promise<Array<string>>;

export function StartBatch(arg1:Array<string>):Promise<void>;
